[package]
name = "soundseekers"
version = "0.1.0"
edition = "2021"

[dependencies]
rimd = "0.0.1"
midly = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "3.1.6"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
